version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    # Defaults to Monday 5am UTC.
    interval: weekly
  open-pull-requests-limit: 20
  reviewers:
  - thomas-anderson-bsl
  - benjamin-wiffen
  labels:
  - dependencies
