name: Build and publish wheel to PYPI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        # fetch all history for all branches and tags, so that our `make` targets can get tags
        with:
          fetch-depth: 0
      - name: Cache Devbox and UV.
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/devbox
            ~/.cache/uv
          key: ${{ runner.os }}-${{ hashFiles('devbox.json', 'pyproject.toml') }}
      - name: Fix tag
        # Workaround actions/checkout bug
        # https://github.com/actions/checkout/issues/290
        # https://github.com/actions/checkout/issues/882
        if: github.ref_type == 'tag'
        run: git fetch -fv origin tag "${GITHUB_REF_NAME}"
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.11.0
      - name: Install depenencies
        run: devbox run -- make venv
      - name: Check python
        run: devbox run -- make check
      - name: Build wheel
        run: devbox run -- make build-wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
