# Uses Changelog Enforcer to check for CHANGELOG.md changes on PRs
# https://github.com/marketplace/actions/changelog-enforcer

name: "Enforce Changelog changes"
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    if: ${{ !(github.actor == 'dependabot[bot]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: dangoslen/changelog-enforcer@v2
        with:
          changeLogPath: "CHANGELOG.md"
          skipLabels: "Skip-Changelog"
          missingUpdateErrorMessage: "PRs must include a CHANGELOG.md update"
