name: Dependabot test and auto-merge
on: pull_request

jobs:
  # Merge pre-conditions.
  test-build-python:
    uses: ./.github/workflows/build_python.yml
  test-codeql-analysis:
    uses: ./.github/workflows/codeql_analysis.yml

  # Merge job.
  dependabot-auto-merge-workflow:
    permissions:
      contents: write
      pull-requests: write
    needs: [test-build-python, test-codeql-analysis]
    uses: brightsparklabs/github-actions/.github/workflows/dependabot-auto-merge.yml@master
    secrets: inherit